apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName}}-deployment
  labels:
    app: {{ .Values.appName}}
spec:
  replicas: {{ .Values.replicaCount}}
  selector:
    matchLabels:
      app: {{ .Values.appName}}
  template:
    metadata:
      labels:
        app: {{ .Values.appName}}
    spec:
      containers:
      - name: {{ .Values.appName}}-container
        image: {{ .Values.imageName}}
        imagePullPolicy: Always
        ports:
        - containerPort: 3001
        envFrom:
        - configMapRef:
            name: {{ .Values.appName}}-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.appName}}-config
data:
  NODE_ENV: production
  PORT: "3001"
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName}}-service
spec:
  type: LoadBalancer
  selector:
    app: {{ .Values.appName}}
  ports:
  - port: 3001
    protocol: TCP
    name: https
    targetPort: 3001
