apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: echo-ingress
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
  - hosts:
    - subdomain1.domain.com
    - subdomain2.domain.com
    secretName: echo-tls
  rules:
    - host: subdomain1.domain.com
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: subdomain1-service
                port:
                  number: 3001
    - host: subdomain2.domain.com
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: subdomain2-service
                port:
                  number: 3000
