apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}-deployment
  labels:
    app: {{ .Values.appName }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec:
      containers:
        - name: {{ .Values.appName }}-container
          image: {{ .Values.imageName }}
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.serviceSourcePort }}
          envFrom:
            - configMapRef:
                name: {{ .Values.appName }}-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.appName }}-config
data:
  NODE_ENV: production
  PORT: {{ .Values.serviceSourcePort | quote }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceName }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.appName }}
  ports:
    - port: {{ .Values.serviceSourcePort }}
      targetPort: {{ .Values.serviceSourcePort }}
      protocol: TCP
